name: CI/CD for Go Application

on:
  push:
    branches:
      - main  # Замените на вашу основную ветку
    tags:
      - v*.*.*  # Запускать job при добавлении тегов вида v1.0.0

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.0'  # Замените на нужную версию Go

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

  publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check secrets
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "DOCKER_USERNAME is not set"
          else
            echo "DOCKER_USERNAME is set"
          fi

          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "DOCKER_PASSWORD is not set"
          else
            echo "DOCKER_PASSWORD is set"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jorg1703/docker-final-ci-cd:${{ github.ref_name }}